name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - "build/*"
      - "src/*"
      - "test/*"
      - "scripts/*"
      
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  source-build:
    uses: ./.github/workflows/test_python.yml

  job2:
    runs-on: ubuntu-latest
    needs: source-build
    steps:
      - run: echo ${{ needs.source-build.outputs.run_id }}

  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      c: ${{ steps.filter.outputs.c }}
      java: ${{ steps.filter.outputs.java }}
      octave: ${{ steps.filter.outputs.octave }}
      rust: ${{ steps.filter.outputs.rust }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          python:
            - "build/python/**"
            - "src/**"
            - "test/**"
          c:
            - "build/c/**"
            - "src/**"
          java:
            - "build/java/**"
            - "src/**"
          octave:
            - "build/octave/**"
            - "src/**"
          rust:
            - "build/rust/**"
            - "src/**"

  python-test:
    needs: [source-build, paths-filter]
    if: needs.paths-filter.outputs.python == 'false'
    uses: ./.github/workflows/test_python.yml

  c-test:
    needs: [source-build, paths-filter]
    if: needs.paths-filter.outputs.c == 'true'
    uses: ./.github/workflows/test_c.yml
 
  java-test:
    needs: [source-build, paths-filter]
    if: needs.paths-filter.outputs.java == 'true'
    uses: ./.github/workflows/test_java.yml

  octave-test:
    needs: [source-build, paths-filter]
    if: needs.paths-filter.outputs.octave == 'true'
    uses: ./.github/workflows/test_octave.yml
  
  rust-test:
    needs: [source-build, paths-filter]
    if: needs.paths-filter.outputs.rust == 'true'
    uses: ./.github/workflows/test_rust.yml
