name: pypi

on:
  workflow_dispatch: # allow triggering workflow manually
    inputs:
      reason:
        description: "Reason for Running"
        required: false
        default: "Manually trigger ci"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  source-build:
    uses: ./.github/workflows/source_build.yml

  pypi-release:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: release
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: dist-python-sdist

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
