name: source-build

on: workflow_call

jobs:
  source-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Setup Python
      run: python -m pip install --upgrade -r scripts/requirements.txt
    - name: Fabricate COCO
      run: python scripts/fabricate
    - name: Run core unit tests
      working-directory: ${{github.workspace}}/test/unit-test/
      run: |
        cmake -B build .
        cmake --build build
        ctest --test-dir build
    - name: Run core integration tests
      working-directory: ${{github.workspace}}/test/integration-test/
      run: |
        cmake -B build .
        cmake --build build
        ctest --test-dir build
    - name: Build coco-experiment Python package
      run: python -m build -s -o dist build/python

 
