name: tag-release

on:
  push:
    # Pattern matched against refs/tags
#    tags:        
#      - '**' # This includes hierarchical tags

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
   
jobs:
  source-build:
    uses: ./.github/workflows/source_build.yml

  release:
    needs: source-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Python source package
        uses: actions/download-artifact@v4
        with:
          name: dist-python-sdist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**


