name: tag-release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' # This includes hierarchical tags
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: ./.github/workflows/source_build.yml
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**


