name: test-rust

on: workflow_call

jobs:
  
  rust-test:
    if: false # Disabled since we don't have any tests yes
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
    - name: Download Rust source package
      uses: actions/download-artifact@v4
      with:
        name: dist-rust
    - name: Unpack
      run: unzip cocoex-rust-*.zip
    - name: Build 
      working-directory: ${{github.workspace}}/cocoex-rust/
      run: cargo build -r
    - name: Test 
      working-directory: ${{github.workspace}}/cocoex-rust/
      run: cargo test -r

  rust-example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
    - name: Download Rust source package
      uses: actions/download-artifact@v4
      with:
        name: dist-rust
    - name: Unpack
      run: unzip cocoex-rust-*.zip
    - name: Build 
      working-directory: ${{github.workspace}}/cocoex-rust/
      run: cargo build -r 
    - name: Example Experiment
      working-directory: ${{github.workspace}}/cocoex-rust/
      run: cargo run --example example-experiment
    - name: Archive Rust example experiment results
      uses: actions/upload-artifact@v4
      with:
        name: rust-example-${{matrix.os}}
        path: cocoex-rust/exdata/*
        
  merge-rust-examples:
    runs-on: ubuntu-latest
    needs: [rust-example]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: rust-examples
          pattern: rust-example-*
          delete-merged: true
