name: test-java

on: workflow_call

jobs:
  java-example:
    strategy:
      matrix:
        # FIXME: Currently fails on windows because of path issues.
        # 
        # Debug and add `windows-latest` back to list at some point.
        os: [ubuntu-latest, macos-14]
        java: [11, 17, 21] 
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
    - name: Download Java source package
      uses: actions/download-artifact@v4
      with:
        name: dist-java
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Unpack
      run: unzip cocoex-java-*.zip
    - name: Build 
      working-directory: ${{github.workspace}}/cocoex-java/
      run: cmake -B build && cmake --build build
    - name: Experiment
      working-directory: ${{github.workspace}}/cocoex-java/
      run: java -classpath build/coco.jar -Djava.library.path=build/ ExampleExperiment 
    - name: Archive Java example experiment results
      uses: actions/upload-artifact@v4
      with:
        name: java-example-${{matrix.os}}-${{matrix.java}}
        path: cocoex-java/exdata/*
        
  merge-java-examples:
    runs-on: ubuntu-latest
    needs: [java-example]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: java-examples
          pattern: java-example-*
          delete-merged: true
