name: valgrind

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allow triggering workflow manually
    inputs:
      reason:
        description: "Reason for Running"
        required: false
        default: "Running valgrind"

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Setup Python
      run: python -m pip install --upgrade -r scripts/requirements.txt
    - name: Fabricate COCO
      run: python scripts/fabricate
    - name: Run core unit tests with valgrind
      working-directory: ${{github.workspace}}/test/unit-test/
      run: |
        cmake -B build .
        cmake --build build
	ctest -T memcheck --test-dir build
